In [3]:
import plotly.express as px
import pandas as pd
data = {
    'Marks' : [40,42,42,41,43,45,44,49,45,42,46,48],
    'Gender':['Male','Female','Male','Female','Male','Female','Male','Female','Male','Female','Male','Female']
}
df = pd.DataFrame(data)
df

    Marks  Gender
0      40    Male
1      42  Female
2      42    Male
3      41  Female
4      43    Male
5      45  Female
6      44    Male
7      49  Female
8      45    Male
9      42  Female
10     46    Male
11     48  Female

In [6]:
pd.get_dummies(df,drop_first=True) #one hot encoding

    Marks  Gender_Male
0      40         True
1      42        False
2      42         True
3      41        False
4      43         True
5      45        False
6      44         True
7      49        False
8      45         True
9      42        False
10     46         True
11     48        False

## Feature creation

In [7]:
df

    Marks  Gender
0      40    Male
1      42  Female
2      42    Male
3      41  Female
4      43    Male
5      45  Female
6      44    Male
7      49  Female
8      45    Male
9      42  Female
10     46    Male
11     48  Female

In [11]:
import numpy as np
df['Result'] = np.where(df['Marks']>45,'Pass','Fail')
df

    Marks  Gender Result
0      40    Male   Fail
1      42  Female   Fail
2      42    Male   Fail
3      41  Female   Fail
4      43    Male   Fail
5      45  Female   Fail
6      44    Male   Fail
7      49  Female   Pass
8      45    Male   Fail
9      42  Female   Fail
10     46    Male   Pass
11     48  Female   Pass

In [17]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'Marks':[42, 44, 46, 48]})

df['Grade'] = np.where(df['Marks'] > 47, 'A',
                np.where(df['Marks'] > 45, 'B',
                np.where(df['Marks'] > 43, 'C', 'D')))

print(df)

   Marks Grade
0     42     D
1     44     C
2     46     B
3     48     A

In [10]:
import plotly.express as px
import pandas as pd
from sklearn.model_selection import train_test_split
data = {
    'Marks' : [40,42,42,41,43,45,44,49,45,42,46,48],
    'Gender':['Male','Female','Male','Female','Male','Female','Male','Female','Male','Female','Male','Female']
}
df = pd.DataFrame(data)
x = df['Gender']
y=df['Marks']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=10)
x_test

2      Male
6      Male
7    Female
Name: Gender, dtype: object

In [5]:
()

()