In [4]:
import pandas as pd                 
df = pd.read_csv ('production_analysis_dataset.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   production_id           50 non-null     int64
 1   product_category        50 non-null     object
 2   factory                 50 non-null     object
 3   shift                   50 non-null     object
 4   supervisor              50 non-null     object
 5   units_produced          50 non-null     int64
 6   defective_units         50 non-null     int64
 7   production_time_hr      50 non-null     float64
 8   machine_downtime_hr     50 non-null     float64
 9   energy_consumption_kwh  50 non-null     int64
 10  profit                  50 non-null     int64
dtypes: float64(2), int64(5), object(4)
memory usage: 4.4+ KB

In [2]:
df.head()

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045

# Q1. Find the total units produced by each product_category.

In [3]:
df.groupby('product_category')['units_produced'].sum()

product_category
Automotive     9408
Electronics    7491
Furniture      7251
Name: units_produced, dtype: int64

# Q2. Calculate the average profit for each factory.

In [4]:
df.groupby('factory')['profit'].mean()

factory
Plant_A    18044.375000
Plant_B    16973.384615
Plant_C    18086.076923
Name: profit, dtype: float64

# Q3. Find the total defective_units for each shift.

In [5]:
df.groupby('shift')['defective_units'].sum()

shift
Evening    132
Morning    472
Night      471
Name: defective_units, dtype: int64

# Q4. Calculate the average production_time_hr for each supervisor.

In [6]:
df.groupby('supervisor')['production_time_hr'].mean()

supervisor
S1    7.801818
S2    7.450000
S3    7.882000
S4    7.956154
Name: production_time_hr, dtype: float64

# Q5. Find the total energy_consumption_kwh for each factory and shift.

In [7]:
df.groupby('factory')['energy_consumption_kwh'].sum()
df.groupby('shift')['energy_consumption_kwh'].sum()

shift
Evening     8433
Morning    24699
Night      25257
Name: energy_consumption_kwh, dtype: int64

# Q6. For each product_category, calculate:
total units_produced
average profit
maximum defective_units.

# Q7. For each factory, calculate:
mean production_time_hr
median machine_downtime_hr.

# Q8. For each shift, compute:
minimum profit
maximum profit
average units_produced.

# Q9. For each supervisor, calculate:
total units_produced
total defective_units.

# Q10. Using apply(), calculate the defect rate for each row:
defect_rate=defective_units/units_produced

# Q11. Using groupby().apply(), find the profit range (max − min) for each factory.

In [5]:
df.groupby('factory').apply(lambda x:x['profit'].max()-x['profit'].min())

C:\Users\LJENG\AppData\Local\Temp\ipykernel_1704\4187880936.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('factory').apply(lambda x:x['profit'].max()-x['profit'].min())

factory
Plant_A    14199
Plant_B    14349
Plant_C    12745
dtype: int64

# Q12. Using groupby().apply(), find the row with maximum units_produced in each product_category.

In [11]:
count=0
for i in df.groupby('product_category'):
    print(i)
    count+=1
    print("this is",count)

df.groupby('product_category').apply(lambda x:x.sort_values(by='units_produced'))

('Automotive',     production_id product_category  factory    shift supervisor  \
0             101       Automotive  Plant_A    Night         S1
1             102       Automotive  Plant_A    Night         S2
9             110       Automotive  Plant_B  Morning         S4
10            111       Automotive  Plant_B    Night         S4
14            115       Automotive  Plant_B    Night         S2
15            116       Automotive  Plant_A  Morning         S3
16            117       Automotive  Plant_B  Evening         S1
19            120       Automotive  Plant_C    Night         S2
20            121       Automotive  Plant_B  Morning         S2
26            127       Automotive  Plant_A  Morning         S1
29            130       Automotive  Plant_A    Night         S3
31            132       Automotive  Plant_A    Night         S1
35            136       Automotive  Plant_C  Morning         S3
37            138       Automotive  Plant_B    Night         S4
41            142       Automotive  Plant_A  Morning         S2
44            145       Automotive  Plant_A  Evening         S3
47            148       Automotive  Plant_A  Evening         S1
48            149       Automotive  Plant_C    Night         S2

    units_produced  defective_units  production_time_hr  machine_downtime_hr  \
0              627               12                6.58                 0.56
1              602               32                6.60                 0.32
9              505               22                6.70                 1.39
10             502               34                6.93                 0.38
14             450               32                6.97                 0.20
15             559               11                9.11                 0.59
16             690               15                8.12                 1.21
19             581               15                7.30                 1.33
20             665               24                7.70                 1.07
26             371               32                7.05                 0.80
29             379               17                7.39                 1.46
31             335                9                8.53                 0.51
35             445               15                7.81                 0.91
37             439               23                8.31                 1.13
41             641               11                7.56                 0.93
44             479               24                8.96                 1.33
47             476               25                7.81                 1.48
48             662               32                6.51                 1.40

    energy_consumption_kwh  profit
0                     1028   12286
1                     1038   18279
9                     1380   24358
10                    1562   19197
14                    1539   24349
15                    1454   18317
16                    1343   10009
19                    1233   13470
20                    1182   17177
26                     877   17260
29                    1393   22054
31                     922   24586
35                    1109   20021
37                    1008   21263
41                    1216   20168
44                    1028   10387
47                     918   16311
48                    1351   21253  )
this is 1
('Electronics',     production_id product_category  factory    shift supervisor  \
2             103      Electronics  Plant_A    Night         S4
3             104      Electronics  Plant_B  Morning         S3
5             106      Electronics  Plant_B  Morning         S2
7             108      Electronics  Plant_B  Evening         S3
8             109      Electronics  Plant_A  Morning         S3
17            118      Electronics  Plant_A    Night         S1
18            119      Electronics  Plant_A    Night         S4
21            122      Electronics  Plant_A  Morning         S1
22            123      Electronics  Plant_B    Night         S4
25            126      Electronics  Plant_A    Night         S4
30            131      Electronics  Plant_C  Morning         S2
36            137      Electronics  Plant_C    Night         S2
38            139      Electronics  Plant_B  Morning         S3
39            140      Electronics  Plant_C  Morning         S1
40            141      Electronics  Plant_B  Morning         S2
46            147      Electronics  Plant_A    Night         S4

    units_produced  defective_units  production_time_hr  machine_downtime_hr  \
2              666               39                7.76                 0.78
3              474               22                6.97                 1.44
5              621               28                8.23                 1.12
7              659                9                8.33                 0.42
8              627               40                7.16                 0.62
17             357               28                9.14                 1.28
18             343               36                8.95                 1.47
21             415                9                7.51                 0.96
22             417                9                9.22                 1.32
25             331               30                8.68                 1.24
30             329                8                8.25                 0.85
36             639               11                9.32                 0.37
38             428                8                6.78                 0.75
39             382               33                8.16                 0.76
40             489               40                6.94                 0.37
46             314               12                9.13                 0.54

    energy_consumption_kwh  profit
2                     1084   23261
3                     1144   11674
5                      846   20834
7                     1546   14010
8                     1586   22713
17                    1114   13923
18                    1345   22547
21                    1035   19641
22                     872   18423
25                     911   14073
30                    1343   12579
36                     918   24577
38                    1083   10722
39                     809   11832
40                    1115   15974
46                    1394   14349  )
this is 2
('Furniture',     production_id product_category  factory    shift supervisor  \
4             105        Furniture  Plant_A    Night         S3
6             107        Furniture  Plant_B  Morning         S3
11            112        Furniture  Plant_A  Morning         S1
12            113        Furniture  Plant_C  Evening         S3
13            114        Furniture  Plant_C  Evening         S1
23            124        Furniture  Plant_A  Evening         S4
24            125        Furniture  Plant_C  Morning         S1
27            128        Furniture  Plant_A  Morning         S4
28            129        Furniture  Plant_C    Night         S4
32            133        Furniture  Plant_A    Night         S3
33            134        Furniture  Plant_A  Morning         S4
34            135        Furniture  Plant_A  Morning         S3
42            143        Furniture  Plant_C    Night         S2
43            144        Furniture  Plant_A  Morning         S4
45            146        Furniture  Plant_C    Night         S3
49            150        Furniture  Plant_C  Morning         S3

    units_produced  defective_units  production_time_hr  machine_downtime_hr  \
4              476               21                8.92                 1.15
6              351               29                7.33                 1.03
11             598               30                7.59                 1.50
12             378               15                8.88                 0.75
13             583                5                8.54                 0.35
23             409               39                6.90                 1.42
24             397               11                6.79                 0.76
27             347               20                7.00                 0.83
28             301               29                7.30                 1.22
32             617               10                7.76                 0.96
33             422               21                7.69                 1.07
34             618               11                6.72                 0.48
42             390               31                6.57                 1.16
43             436               15                8.86                 0.34
45             442                9                9.40                 0.56
49             486               32                6.71                 1.06

    energy_consumption_kwh  profit
4                     1349   12045
6                     1173   12664
11                     941   18348
12                     865   16304
13                    1349   22302
23                    1384   19440
24                    1233   16735
27                    1018   24166
28                    1265   14673
32                    1335   15183
33                    1107   17491
34                    1071   12170
42                    1140   22818
43                     839   24067
45                    1456   18346
49                    1138   20209  )
this is 3

C:\Users\LJENG\AppData\Local\Temp\ipykernel_1704\2931161636.py:7: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('product_category').apply(lambda x:x.sort_values(by='units_produced'))

                     production_id product_category  factory    shift  \
product_category
Automotive       31            132       Automotive  Plant_A    Night
                 26            127       Automotive  Plant_A  Morning
                 29            130       Automotive  Plant_A    Night
                 37            138       Automotive  Plant_B    Night
                 35            136       Automotive  Plant_C  Morning
                 14            115       Automotive  Plant_B    Night
                 47            148       Automotive  Plant_A  Evening
                 44            145       Automotive  Plant_A  Evening
                 10            111       Automotive  Plant_B    Night
                 9             110       Automotive  Plant_B  Morning
                 15            116       Automotive  Plant_A  Morning
                 19            120       Automotive  Plant_C    Night
                 1             102       Automotive  Plant_A    Night
                 0             101       Automotive  Plant_A    Night
                 41            142       Automotive  Plant_A  Morning
                 48            149       Automotive  Plant_C    Night
                 20            121       Automotive  Plant_B  Morning
                 16            117       Automotive  Plant_B  Evening
Electronics      46            147      Electronics  Plant_A    Night
                 30            131      Electronics  Plant_C  Morning
                 25            126      Electronics  Plant_A    Night
                 18            119      Electronics  Plant_A    Night
                 17            118      Electronics  Plant_A    Night
                 39            140      Electronics  Plant_C  Morning
                 21            122      Electronics  Plant_A  Morning
                 22            123      Electronics  Plant_B    Night
                 38            139      Electronics  Plant_B  Morning
                 3             104      Electronics  Plant_B  Morning
                 40            141      Electronics  Plant_B  Morning
                 5             106      Electronics  Plant_B  Morning
                 8             109      Electronics  Plant_A  Morning
                 36            137      Electronics  Plant_C    Night
                 7             108      Electronics  Plant_B  Evening
                 2             103      Electronics  Plant_A    Night
Furniture        28            129        Furniture  Plant_C    Night
                 27            128        Furniture  Plant_A  Morning
                 6             107        Furniture  Plant_B  Morning
                 12            113        Furniture  Plant_C  Evening
                 42            143        Furniture  Plant_C    Night
                 24            125        Furniture  Plant_C  Morning
                 23            124        Furniture  Plant_A  Evening
                 33            134        Furniture  Plant_A  Morning
                 43            144        Furniture  Plant_A  Morning
                 45            146        Furniture  Plant_C    Night
                 4             105        Furniture  Plant_A    Night
                 49            150        Furniture  Plant_C  Morning
                 13            114        Furniture  Plant_C  Evening
                 11            112        Furniture  Plant_A  Morning
                 32            133        Furniture  Plant_A    Night
                 34            135        Furniture  Plant_A  Morning

                    supervisor  units_produced  defective_units  \
product_category
Automotive       31         S1             335                9
                 26         S1             371               32
                 29         S3             379               17
                 37         S4             439               23
                 35         S3             445               15
                 14         S2             450               32
                 47         S1             476               25
                 44         S3             479               24
                 10         S4             502               34
                 9          S4             505               22
                 15         S3             559               11
                 19         S2             581               15
                 1          S2             602               32
                 0          S1             627               12
                 41         S2             641               11
                 48         S2             662               32
                 20         S2             665               24
                 16         S1             690               15
Electronics      46         S4             314               12
                 30         S2             329                8
                 25         S4             331               30
                 18         S4             343               36
                 17         S1             357               28
                 39         S1             382               33
                 21         S1             415                9
                 22         S4             417                9
                 38         S3             428                8
                 3          S3             474               22
                 40         S2             489               40
                 5          S2             621               28
                 8          S3             627               40
                 36         S2             639               11
                 7          S3             659                9
                 2          S4             666               39
Furniture        28         S4             301               29
                 27         S4             347               20
                 6          S3             351               29
                 12         S3             378               15
                 42         S2             390               31
                 24         S1             397               11
                 23         S4             409               39
                 33         S4             422               21
                 43         S4             436               15
                 45         S3             442                9
                 4          S3             476               21
                 49         S3             486               32
                 13         S1             583                5
                 11         S1             598               30
                 32         S3             617               10
                 34         S3             618               11

                     production_time_hr  machine_downtime_hr  \
product_category
Automotive       31                8.53                 0.51
                 26                7.05                 0.80
                 29                7.39                 1.46
                 37                8.31                 1.13
                 35                7.81                 0.91
                 14                6.97                 0.20
                 47                7.81                 1.48
                 44                8.96                 1.33
                 10                6.93                 0.38
                 9                 6.70                 1.39
                 15                9.11                 0.59
                 19                7.30                 1.33
                 1                 6.60                 0.32
                 0                 6.58                 0.56
                 41                7.56                 0.93
                 48                6.51                 1.40
                 20                7.70                 1.07
                 16                8.12                 1.21
Electronics      46                9.13                 0.54
                 30                8.25                 0.85
                 25                8.68                 1.24
                 18                8.95                 1.47
                 17                9.14                 1.28
                 39                8.16                 0.76
                 21                7.51                 0.96
                 22                9.22                 1.32
                 38                6.78                 0.75
                 3                 6.97                 1.44
                 40                6.94                 0.37
                 5                 8.23                 1.12
                 8                 7.16                 0.62
                 36                9.32                 0.37
                 7                 8.33                 0.42
                 2                 7.76                 0.78
Furniture        28                7.30                 1.22
                 27                7.00                 0.83
                 6                 7.33                 1.03
                 12                8.88                 0.75
                 42                6.57                 1.16
                 24                6.79                 0.76
                 23                6.90                 1.42
                 33                7.69                 1.07
                 43                8.86                 0.34
                 45                9.40                 0.56
                 4                 8.92                 1.15
                 49                6.71                 1.06
                 13                8.54                 0.35
                 11                7.59                 1.50
                 32                7.76                 0.96
                 34                6.72                 0.48

                     energy_consumption_kwh  profit
product_category
Automotive       31                     922   24586
                 26                     877   17260
                 29                    1393   22054
                 37                    1008   21263
                 35                    1109   20021
                 14                    1539   24349
                 47                     918   16311
                 44                    1028   10387
                 10                    1562   19197
                 9                     1380   24358
                 15                    1454   18317
                 19                    1233   13470
                 1                     1038   18279
                 0                     1028   12286
                 41                    1216   20168
                 48                    1351   21253
                 20                    1182   17177
                 16                    1343   10009
Electronics      46                    1394   14349
                 30                    1343   12579
                 25                     911   14073
                 18                    1345   22547
                 17                    1114   13923
                 39                     809   11832
                 21                    1035   19641
                 22                     872   18423
                 38                    1083   10722
                 3                     1144   11674
                 40                    1115   15974
                 5                      846   20834
                 8                     1586   22713
                 36                     918   24577
                 7                     1546   14010
                 2                     1084   23261
Furniture        28                    1265   14673
                 27                    1018   24166
                 6                     1173   12664
                 12                     865   16304
                 42                    1140   22818
                 24                    1233   16735
                 23                    1384   19440
                 33                    1107   17491
                 43                     839   24067
                 45                    1456   18346
                 4                     1349   12045
                 49                    1138   20209
                 13                    1349   22302
                 11                     941   18348
                 32                    1335   15183
                 34                    1071   12170

# Q13. Use apply() to create a new column efficiency_score:
efficiency=units_produced/production_time_hr

In [17]:
df['efficiency_score'] = df.apply(
    lambda x:x['units_produced']/x['production_time_hr'],axis=1
)
df

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit,efficiency_score
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286,95.288754
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279,91.212121
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261,85.824742
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674,68.005739
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045,53.363229
5,106,Electronics,Plant_B,Morning,S2,621,28,8.23,1.12,846,20834,75.455650
6,107,Furniture,Plant_B,Morning,S3,351,29,7.33,1.03,1173,12664,47.885402
7,108,Electronics,Plant_B,Evening,S3,659,9,8.33,0.42,1546,14010,79.111645
8,109,Electronics,Plant_A,Morning,S3,627,40,7.16,0.62,1586,22713,87.569832
9,110,Automotive,Plant_B,Morning,S4,505,22,6.70,1.39,1380,24358,75.373134
10,111,Automotive,Plant_B,Night,S4,502,34,6.93,0.38,1562,19197,72.438672
11,112,Furniture,Plant_A,Morning,S1,598,30,7.59,1.50,941,18348,78.787879
12,113,Furniture,Plant_C,Evening,S3,378,15,8.88,0.75,865,16304,42.567568
13,114,Furniture,Plant_C,Evening,S1,583,5,8.54,0.35,1349,22302,68.266979
14,115,Automotive,Plant_B,Night,S2,450,32,6.97,0.20,1539,24349,64.562410
15,116,Automotive,Plant_A,Morning,S3,559,11,9.11,0.59,1454,18317,61.361142
16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009,84.975369
17,118,Electronics,Plant_A,Night,S1,357,28,9.14,1.28,1114,13923,39.059081
18,119,Electronics,Plant_A,Night,S4,343,36,8.95,1.47,1345,22547,38.324022
19,120,Automotive,Plant_C,Night,S2,581,15,7.30,1.33,1233,13470,79.589041
20,121,Automotive,Plant_B,Morning,S2,665,24,7.70,1.07,1182,17177,86.363636
21,122,Electronics,Plant_A,Morning,S1,415,9,7.51,0.96,1035,19641,55.259654
22,123,Electronics,Plant_B,Night,S4,417,9,9.22,1.32,872,18423,45.227766
23,124,Furniture,Plant_A,Evening,S4,409,39,6.90,1.42,1384,19440,59.275362
24,125,Furniture,Plant_C,Morning,S1,397,11,6.79,0.76,1233,16735,58.468336
25,126,Electronics,Plant_A,Night,S4,331,30,8.68,1.24,911,14073,38.133641
26,127,Automotive,Plant_A,Morning,S1,371,32,7.05,0.80,877,17260,52.624113
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166,49.571429
28,129,Furniture,Plant_C,Night,S4,301,29,7.30,1.22,1265,14673,41.232877
29,130,Automotive,Plant_A,Night,S3,379,17,7.39,1.46,1393,22054,51.285521
30,131,Electronics,Plant_C,Morning,S2,329,8,8.25,0.85,1343,12579,39.878788
31,132,Automotive,Plant_A,Night,S1,335,9,8.53,0.51,922,24586,39.273154
32,133,Furniture,Plant_A,Night,S3,617,10,7.76,0.96,1335,15183,79.510309
33,134,Furniture,Plant_A,Morning,S4,422,21,7.69,1.07,1107,17491,54.876463
34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170,91.964286
35,136,Automotive,Plant_C,Morning,S3,445,15,7.81,0.91,1109,20021,56.978233
36,137,Electronics,Plant_C,Night,S2,639,11,9.32,0.37,918,24577,68.562232
37,138,Automotive,Plant_B,Night,S4,439,23,8.31,1.13,1008,21263,52.827918
38,139,Electronics,Plant_B,Morning,S3,428,8,6.78,0.75,1083,10722,63.126844
39,140,Electronics,Plant_C,Morning,S1,382,33,8.16,0.76,809,11832,46.813725
40,141,Electronics,Plant_B,Morning,S2,489,40,6.94,0.37,1115,15974,70.461095
41,142,Automotive,Plant_A,Morning,S2,641,11,7.56,0.93,1216,20168,84.788360
42,143,Furniture,Plant_C,Night,S2,390,31,6.57,1.16,1140,22818,59.360731
43,144,Furniture,Plant_A,Morning,S4,436,15,8.86,0.34,839,24067,49.209932
44,145,Automotive,Plant_A,Evening,S3,479,24,8.96,1.33,1028,10387,53.459821
45,146,Furniture,Plant_C,Night,S3,442,9,9.40,0.56,1456,18346,47.021277
46,147,Electronics,Plant_A,Night,S4,314,12,9.13,0.54,1394,14349,34.392114
47,148,Automotive,Plant_A,Evening,S1,476,25,7.81,1.48,918,16311,60.947503
48,149,Automotive,Plant_C,Night,S2,662,32,6.51,1.40,1351,21253,101.689708
49,150,Furniture,Plant_C,Morning,S3,486,32,6.71,1.06,1138,20209,72.429210

# Q14. Find how many times each product_category appears in the dataset.

In [15]:
df['product_category'].value_counts()

product_category
Automotive     18
Electronics    16
Furniture      16
Name: count, dtype: int64

# Q15. Count the number of records for each shift.

In [16]:
df['shift'].value_counts()

shift
Morning    22
Night      21
Evening     7
Name: count, dtype: int64

# Q16. Find the most frequent supervisor using value_counts().

In [19]:
df['supervisor'].value_counts().head(1)

supervisor
S3    15
Name: count, dtype: int64

# Q17. Sort the dataset by profit in descending order.

In [20]:
df.sort_values(by='profit',ascending=False)

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit,efficiency_score
31,132,Automotive,Plant_A,Night,S1,335,9,8.53,0.51,922,24586,39.273154
36,137,Electronics,Plant_C,Night,S2,639,11,9.32,0.37,918,24577,68.562232
9,110,Automotive,Plant_B,Morning,S4,505,22,6.70,1.39,1380,24358,75.373134
14,115,Automotive,Plant_B,Night,S2,450,32,6.97,0.20,1539,24349,64.562410
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166,49.571429
43,144,Furniture,Plant_A,Morning,S4,436,15,8.86,0.34,839,24067,49.209932
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261,85.824742
42,143,Furniture,Plant_C,Night,S2,390,31,6.57,1.16,1140,22818,59.360731
8,109,Electronics,Plant_A,Morning,S3,627,40,7.16,0.62,1586,22713,87.569832
18,119,Electronics,Plant_A,Night,S4,343,36,8.95,1.47,1345,22547,38.324022
13,114,Furniture,Plant_C,Evening,S1,583,5,8.54,0.35,1349,22302,68.266979
29,130,Automotive,Plant_A,Night,S3,379,17,7.39,1.46,1393,22054,51.285521
37,138,Automotive,Plant_B,Night,S4,439,23,8.31,1.13,1008,21263,52.827918
48,149,Automotive,Plant_C,Night,S2,662,32,6.51,1.40,1351,21253,101.689708
5,106,Electronics,Plant_B,Morning,S2,621,28,8.23,1.12,846,20834,75.455650
49,150,Furniture,Plant_C,Morning,S3,486,32,6.71,1.06,1138,20209,72.429210
41,142,Automotive,Plant_A,Morning,S2,641,11,7.56,0.93,1216,20168,84.788360
35,136,Automotive,Plant_C,Morning,S3,445,15,7.81,0.91,1109,20021,56.978233
21,122,Electronics,Plant_A,Morning,S1,415,9,7.51,0.96,1035,19641,55.259654
23,124,Furniture,Plant_A,Evening,S4,409,39,6.90,1.42,1384,19440,59.275362
10,111,Automotive,Plant_B,Night,S4,502,34,6.93,0.38,1562,19197,72.438672
22,123,Electronics,Plant_B,Night,S4,417,9,9.22,1.32,872,18423,45.227766
11,112,Furniture,Plant_A,Morning,S1,598,30,7.59,1.50,941,18348,78.787879
45,146,Furniture,Plant_C,Night,S3,442,9,9.40,0.56,1456,18346,47.021277
15,116,Automotive,Plant_A,Morning,S3,559,11,9.11,0.59,1454,18317,61.361142
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279,91.212121
33,134,Furniture,Plant_A,Morning,S4,422,21,7.69,1.07,1107,17491,54.876463
26,127,Automotive,Plant_A,Morning,S1,371,32,7.05,0.80,877,17260,52.624113
20,121,Automotive,Plant_B,Morning,S2,665,24,7.70,1.07,1182,17177,86.363636
24,125,Furniture,Plant_C,Morning,S1,397,11,6.79,0.76,1233,16735,58.468336
47,148,Automotive,Plant_A,Evening,S1,476,25,7.81,1.48,918,16311,60.947503
12,113,Furniture,Plant_C,Evening,S3,378,15,8.88,0.75,865,16304,42.567568
40,141,Electronics,Plant_B,Morning,S2,489,40,6.94,0.37,1115,15974,70.461095
32,133,Furniture,Plant_A,Night,S3,617,10,7.76,0.96,1335,15183,79.510309
28,129,Furniture,Plant_C,Night,S4,301,29,7.30,1.22,1265,14673,41.232877
46,147,Electronics,Plant_A,Night,S4,314,12,9.13,0.54,1394,14349,34.392114
25,126,Electronics,Plant_A,Night,S4,331,30,8.68,1.24,911,14073,38.133641
7,108,Electronics,Plant_B,Evening,S3,659,9,8.33,0.42,1546,14010,79.111645
17,118,Electronics,Plant_A,Night,S1,357,28,9.14,1.28,1114,13923,39.059081
19,120,Automotive,Plant_C,Night,S2,581,15,7.30,1.33,1233,13470,79.589041
6,107,Furniture,Plant_B,Morning,S3,351,29,7.33,1.03,1173,12664,47.885402
30,131,Electronics,Plant_C,Morning,S2,329,8,8.25,0.85,1343,12579,39.878788
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286,95.288754
34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170,91.964286
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045,53.363229
39,140,Electronics,Plant_C,Morning,S1,382,33,8.16,0.76,809,11832,46.813725
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674,68.005739
38,139,Electronics,Plant_B,Morning,S3,428,8,6.78,0.75,1083,10722,63.126844
44,145,Automotive,Plant_A,Evening,S3,479,24,8.96,1.33,1028,10387,53.459821
16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009,84.975369

# Q18. Sort the dataset by:
•	product_category ascending
•	units_produced descending

In [23]:
df.sort_values(by=['product_category','units_produced'],ascending=[True,False])

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit,efficiency_score
16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009,84.975369
20,121,Automotive,Plant_B,Morning,S2,665,24,7.70,1.07,1182,17177,86.363636
48,149,Automotive,Plant_C,Night,S2,662,32,6.51,1.40,1351,21253,101.689708
41,142,Automotive,Plant_A,Morning,S2,641,11,7.56,0.93,1216,20168,84.788360
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286,95.288754
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279,91.212121
19,120,Automotive,Plant_C,Night,S2,581,15,7.30,1.33,1233,13470,79.589041
15,116,Automotive,Plant_A,Morning,S3,559,11,9.11,0.59,1454,18317,61.361142
9,110,Automotive,Plant_B,Morning,S4,505,22,6.70,1.39,1380,24358,75.373134
10,111,Automotive,Plant_B,Night,S4,502,34,6.93,0.38,1562,19197,72.438672
44,145,Automotive,Plant_A,Evening,S3,479,24,8.96,1.33,1028,10387,53.459821
47,148,Automotive,Plant_A,Evening,S1,476,25,7.81,1.48,918,16311,60.947503
14,115,Automotive,Plant_B,Night,S2,450,32,6.97,0.20,1539,24349,64.562410
35,136,Automotive,Plant_C,Morning,S3,445,15,7.81,0.91,1109,20021,56.978233
37,138,Automotive,Plant_B,Night,S4,439,23,8.31,1.13,1008,21263,52.827918
29,130,Automotive,Plant_A,Night,S3,379,17,7.39,1.46,1393,22054,51.285521
26,127,Automotive,Plant_A,Morning,S1,371,32,7.05,0.80,877,17260,52.624113
31,132,Automotive,Plant_A,Night,S1,335,9,8.53,0.51,922,24586,39.273154
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261,85.824742
7,108,Electronics,Plant_B,Evening,S3,659,9,8.33,0.42,1546,14010,79.111645
36,137,Electronics,Plant_C,Night,S2,639,11,9.32,0.37,918,24577,68.562232
8,109,Electronics,Plant_A,Morning,S3,627,40,7.16,0.62,1586,22713,87.569832
5,106,Electronics,Plant_B,Morning,S2,621,28,8.23,1.12,846,20834,75.455650
40,141,Electronics,Plant_B,Morning,S2,489,40,6.94,0.37,1115,15974,70.461095
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674,68.005739
38,139,Electronics,Plant_B,Morning,S3,428,8,6.78,0.75,1083,10722,63.126844
22,123,Electronics,Plant_B,Night,S4,417,9,9.22,1.32,872,18423,45.227766
21,122,Electronics,Plant_A,Morning,S1,415,9,7.51,0.96,1035,19641,55.259654
39,140,Electronics,Plant_C,Morning,S1,382,33,8.16,0.76,809,11832,46.813725
17,118,Electronics,Plant_A,Night,S1,357,28,9.14,1.28,1114,13923,39.059081
18,119,Electronics,Plant_A,Night,S4,343,36,8.95,1.47,1345,22547,38.324022
25,126,Electronics,Plant_A,Night,S4,331,30,8.68,1.24,911,14073,38.133641
30,131,Electronics,Plant_C,Morning,S2,329,8,8.25,0.85,1343,12579,39.878788
46,147,Electronics,Plant_A,Night,S4,314,12,9.13,0.54,1394,14349,34.392114
34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170,91.964286
32,133,Furniture,Plant_A,Night,S3,617,10,7.76,0.96,1335,15183,79.510309
11,112,Furniture,Plant_A,Morning,S1,598,30,7.59,1.50,941,18348,78.787879
13,114,Furniture,Plant_C,Evening,S1,583,5,8.54,0.35,1349,22302,68.266979
49,150,Furniture,Plant_C,Morning,S3,486,32,6.71,1.06,1138,20209,72.429210
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045,53.363229
45,146,Furniture,Plant_C,Night,S3,442,9,9.40,0.56,1456,18346,47.021277
43,144,Furniture,Plant_A,Morning,S4,436,15,8.86,0.34,839,24067,49.209932
33,134,Furniture,Plant_A,Morning,S4,422,21,7.69,1.07,1107,17491,54.876463
23,124,Furniture,Plant_A,Evening,S4,409,39,6.90,1.42,1384,19440,59.275362
24,125,Furniture,Plant_C,Morning,S1,397,11,6.79,0.76,1233,16735,58.468336
42,143,Furniture,Plant_C,Night,S2,390,31,6.57,1.16,1140,22818,59.360731
12,113,Furniture,Plant_C,Evening,S3,378,15,8.88,0.75,865,16304,42.567568
6,107,Furniture,Plant_B,Morning,S3,351,29,7.33,1.03,1173,12664,47.885402
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166,49.571429
28,129,Furniture,Plant_C,Night,S4,301,29,7.30,1.22,1265,14673,41.232877